go-sprout/sprout

.gitignore
alias.go
alias_test.go
functions.go
functions_test.go
sprout.go

This pull request introduces the aliasing feature in the update allows for backward compatibility by mapping old function names to their updated versions. This ensures legacy code remains functional while encouraging the adoption of new naming conventions without breaking existing projects.

feat: allow functions aliasing 🌱

---

conversion_functions.go
conversion_functions_test.go
sprout.go

This pull request introduce the `toDuration` as proposed in #8 and https://github.com/Masterminds/sprig/issues/388 using the `cast` package.
- Add the function `toDuration`

feat: introduce toduration conversion function

---

benchmarks/go.mod
sprig_backward_compatibility.go
sprig_backward_compatibility_test.go

This pull request reimports several functions from the Sprig library to maintain backward compatibility. This is marked as a regression issue
- Reimported `HermeticTxtFuncMap`, `HermeticHtmlFuncMap`, `TxtFuncMap`, `HtmlFuncMap`, `GenericFuncMap` from Sprig.

fix(backward): reimport functions from sprig to maintain backward compatibility

---

conversion_functions.go
conversion_functions_test.go
sprout.go

This pull request introduces three new functions `toBool`, `toUint` and `toUint64` to the conversion group
- New functions: `toBool`, `toUint` and `toUint64`
- All conversion function are documented on https://docs.atom.codes/sprout

feat: add functions and docs to conversions group

---

maps_functions.go
maps_functions_test.go

Backport fix of sprig into sprout, initially provided by @huww98

fix: merge should preserve zero value in dest

---

strings_functions.go
strings_functions_test.go

In sprig, `camelCase` return a `PascalCase` and don't respect the separation logic between both functions.
- Introduce a `toPascalCase` function to transform a string to a `PascalCase`
- Fix the behivour of `toCamelCase` function to transform a string to a `camelCase`
This edit are related to https://github.com/Masterminds/sprig/issues/328
Backport ticket from @ghostsquad

fix: camelcase and pascalcase transformation logic

---

encoding_functions.go
encoding_functions_test.go
go.mod
go.sum
sprout.go

We continue to backport features, bug fixes, and more from Sprig to Sprout. This time, I'm focusing on the YAML functions part, used by Helm and intended for use by others as well.
- Add `fromYaml` function to convert yaml string into a go map
- Add `toYaml` function to convert any to a yaml string
- Add `mustFromYaml` function to convert and return error to the template system when occurs 
- Add `mustToYaml` function to convert and return error to the template system when occurs 
The documentation for the encoding part of the library will be released soon after this pull request on https://sprout.atom.codes
Initially implemented by @blakepettersson on sprig

feat: implement yaml functions based on helm implementation

---

encoding_functions.go
encoding_functions_test.go
go.mod
go.sum

Noticed that k8s suddenly appeared in my dependencies. Since this only adds yaml2json features it's not necessary here.
- Replace sigs yaml deps by go-yaml
Follow-up to https://github.com/go-sprout/sprout/pull/36

chore: reduce yaml dependencies footprint

---

conversion_functions_test.go

This pull request resolve issue when run test locally on an other timezone than UTC.
- Fix the `TestMustToDate` to enforce UTC
This raise a point to missing management of timezone in lib

fix: timezone leak in to date method

---

SPRIG_TO_SPROUT_CHANGES_NOTES.md
numeric_functions.go
sprig_backward_compatibility.go

Few variables and methods don't have the mention for backward compatibility only. Also two changes of sprout has not clearly identified in the temporary list in **SPRIG_TO_SPROUT_CHANGES_NOTES.md** file. 
- Add documentation line on backward functions
- Add changes on the SPRIG_TO_SPROUT_CHANGES_NOTES.md file
_The file **SPRIG_TO_SPROUT_CHANGES_NOTES.md** will be moved in the future on the documentation site_

docs: add documentation for backward compatibilities

---

docs/functions/type-conversions.md

I use Go templates to produce machine-readable files, and one of the challenges I face is producing amounts of time as seconds and milliseconds. I want to write values like "5 minutes" or "30 seconds" for the benefit of file maintainers and have a computer do the math to turn them into numbers.
The `toDuration` function satisfies my use case and seems valuable to show in the documentation.
One more example for the `toDuration` function.
This example matches this test: https://github.com/go-sprout/sprout/blob/aca5c32cd0f8340e64998aa718dee2b3564717d4/conversion_functions_test.go#L130

docs: show conversion from duration to seconds

---

sprout.go

The default logger aren't initialized correctly causing crash when using the default logger without opts.
- The default logger will now print on `stdout`

fix: default logger have a bad init

---

docs/advanced/how-to-create-a-registry.md
registry/_example/_example.go
registry/backward/backward.go
registry/checksum/checksum.go
registry/conversion/conversion.go
registry/crypto/crypto.go
registry/encoding/encoding.go
registry/env/env.go
registry/filesystem/filesystem.go
registry/maps/maps.go
registry/numeric/numeric.go
registry/random/random.go
registry/reflect/reflect.go
registry/regexp/regexp.go
registry/semver/semver.go
registry/slices/slices.go
registry/std/std.go
registry/strings/strings.go
registry/time/time.go
registry/uniqueid/uniqueid.go

Handler are sent to registry over a double pointer causing inaccessible handler features. 
- Use a pointer instead of double pointer.

fix: logger aren't accessible due to duplicated pointer

---

sprigin/sprig_backward_compatibility.go

In sprig, `camelcase` return a pascalcase. In Sprout we have both functions but as `sprigin` must be a no-breaking replacement, `camelcase` needs to still be "bugged" 😢 
- Use alias to provide backward compatibility

fix: sprigin camelcase needs to be the same (bugged) return

---

.github/workflows/test.yaml
SPRIG_TO_SPROUT_CHANGES_NOTES.md
benchmarks/allFunctions.sprig.tmpl
benchmarks/allFunctionsAsSprig.sprout.tmpl
benchmarks/comparaison_test.go
benchmarks/compare.tmpl
docs/registries/crypto.md
internal/helpers/helpers.go
registry/conversion/functions.go
registry/crypto/functions.go
registry/crypto/helpers.go
registry/maps/functions.go
registry/numeric/helpers.go
registry/numeric/helpers_test.go
registry/random/helpers.go
registry/slices/functions.go
registry/slices/functions_test.go
registry/slices/helpers.go
registry/slices/helpers_test.go
registry/std/functions.go
registry/std/functions_test.go
registry/strings/functions.go
registry/time/functions.go
registry/time/functions_test.go
sprigin/sprig_backward_compatibility.go
taskfile.yml

Aim to minimize memory allocations as much as possible to alleviate the burden on the garbage collector in large-scale applications. By optimizing the way memory is used within the framework, we ensure that Sprout is not only efficient in its functionality but also in its resource consumption. This approach contributes to overall better performance and scalability of applications using Sprout.
- Reduce allocations over all functions
- Increase garbage-collector capacity over all functions
- Introduce a robust compare tool to ensure no breaking change are present between sprig and sprout
Somes functions output are incorrect by definition in Sprig and Sprout fix that 🎉 
A list are presented in `SPRIG_TO_SPROUT_CHANGES_NOTES.md` and needs to be migrated in official documentation

perf: reduce all memory fingerprint

---

benchmarks/comparaison_test.go
handler.go
handler_test.go
notice.go
notice_test.go
registry.go
registry/numeric/numeric.go
sprigin/sprig_backward_compatibility.go
sprout.go

When you are a middle-app (between sprout and the user how write the template), you need to be careful when you upgrade a template library due to potential breaking changes or deprecated functions. This solution let developer be stress less about upgrade of sprout 🌱
- Add notice feature
- Add notice on numeric registry
- Add notice on sprigin package
Example of output using a custom `slog.Logger`

feat: add notice on function call to inform or warn the end-users

---

docs/registries/checksum.md
registry/checksum/checksum.go
registry/checksum/functions.go
registry/checksum/functions_test.go
sprigin/sprig_backward_compatibility_test.go

Introduce the `sha512Sum` function as requested by sprig community and update old functions to new standards (naming convention and notice for deprecation) to `checksum` registry
- Add `sha512Sum` function to `checksum` registry
- Add error return to each method of the registry
- Add notice to deprecate old naming `sha1sum` -> `sha1Sum`
Documentation update are embed

feat: add sha512sum to checksum registry and add notices

---

docs/registries/reflect.md
registry/reflect/functions.go
registry/reflect/functions_test.go
registry/reflect/reflect.go

Closes #60 
The PR introduces a `hasField` method to the `reflect` registry, to address the use case explained in #60.

feat: add `hasField` method for use with structs

---

docs/registries/strings.md
registry/strings/functions.go
registry/strings/functions_test.go
registry/strings/strings.go

When we manipulate strings in template, we need sometimes to capitalize or uncapitalize a string. A good example are when we manipulate go file and want to turn public/private functions.
- Add `capitalize` functions on strings registry
- Add `uncapitalize` functions on strings registry

feat: add strings capitalization functions

---

registry/strings/functions.go
registry/strings/functions_test.go
registry/strings/helpers.go

`capitalize` and `uncapitalize` have untested statement with latin and unicode rune. Decode rune stored in multiple byte correctly.
Source of the report : https://github.com/go-sprout/sprout/pull/62#discussion_r1727405631 reported by @ccoVeille

fix: capitalize with unicode and latin runes

---

docs/introduction/templating-conventions.md

Functions signatures convention have not be write on the documentation, this pull request added it. 
- Add convention about functions signatures

docs: add functions signature in conventions

---

alias.go
alias_test.go
docs/advanced/how-to-create-a-handler.md
docs/features/loader-system-registry.md
docs/introduction/getting-started.md
handler.go
handler_test.go
notice.go
notice_test.go
registry.go
registry_test.go
sprigin/sprig_backward_compatibility.go
sprigin/sprig_backward_compatibility_test.go
sprout.go
sprout_test.go

This pull requests grabs returns for the `v0.6.0-rc.1` (Release Candidate 1) and resolve issues related to it. 
- Add `Raw` prefix to `Functions` and `Aliases` function to be more comprehensible and prevent confusion with `Funcs()` from sprig.
- Remove deprecated `NewFunctionhandler` labelled as deprecated in v0.2.0 to prepare the `v1.0.0`
- Ensure a built function map cannot be rebuild and cause memory growing
- Prevent to creating an alias on a no-existant function name

fix: resolve issues with the v0.6.0-rc.1

---

docs/advanced/how-to-create-a-registry.md
handler_test.go
registry.go
registry/_example/_example.go
registry/backward/backward.go
registry/checksum/checksum.go
registry/conversion/conversion.go
registry/crypto/crypto.go
registry/encoding/encoding.go
registry/env/env.go
registry/filesystem/filesystem.go
registry/maps/maps.go
registry/network/network.go
registry/numeric/numeric.go
registry/random/random.go
registry/reflect/reflect.go
registry/regexp/regexp.go
registry/semver/semver.go
registry/slices/slices.go
registry/std/std.go
registry/strings/strings.go
registry/time/time.go
registry/uniqueid/uniqueid.go
registry_test.go
sprigin/sprig_backward_compatibility_test.go

In documentation we ask to have a clear Uid definition but we don't follow this rule inside the sprout package.
- Add the organization and repo name in all package UID
- Turn UID un lowercase (to help future implementation)

chore: follow sprout conventions internally

---

.golangci.yaml
benchmarks/comparison_test.go
docs/registries/conversion.md
docs/registries/time.md
handler.go
pesticide/time_test_helpers.go
registry/conversion/functions.go
registry/conversion/functions_test.go
registry/time/functions.go
registry/time/functions_test.go
registry/time/helpers.go
registry/time/helpers_test.go
sprigin/sprig_backward_compatibility.go

It's important to use the date timezone if it has any.
Do not switch back to Local timezone if not needed
Timezones are always fun

fix(date): use available timezone if any
